name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache do Cargo (para acelerar builds futuros)
        uses: Swatinem/rust-cache@v2

      - name: Compilar o projeto
        working-directory: teste
        run: cargo build --release

      - name: Executar testes (se houver)
        working-directory: teste
        run: cargo test --verbose

      - name: Executar código principal
        working-directory: teste
        run: cargo run
